### ISSUE TITLE
Missing Include

### ISSUE THREAD

**Issue by rafaelmartines** [garciadev/cbSwaggerUI#1]
Hi, I'm trying to use this module, but even in coldbox clean install using the REST API template, I'm getting this error:

MissingInclude
Could not find the included template //views/Main/index.cfm.

I thought that it was something related to my Router.cfc, but I can't figure out what's going on.

![image](https://github.com/garciadev/cbSwaggerUI/assets/8183691/32b60775-3ba5-49df-862e-4543650c7e92)

I already has cbswagger and swagger-sdk installed

**Comment by rafaelmartines** [comment]
Hi, I discovered the issue, working on my Windows machine the module started working and on my Linux machine the bug persisted, since Windows is not case sensitive, I realized that when I install the module, it creates a folder named "main" in lower case and in the ModuleConfig.cfc you try to get a folder in uppercase (Main), after I adjusted to lowercase and executed reinit the module started to work again on Linux machine.

![image](https://github.com/garciadev/cbSwaggerUI/assets/8183691/4b531892-c48a-4e89-9849-21310fcbaa41)

**Comment by garciadev** [comment]
I updated ModuleConfig to make all references to Main lowercase. I also renamed the layout to lowercase to make it consistent.
